<?php
/**
 * File product_comments.phtml
 * Created: 14.03.2011
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * It is available through the world-wide-web at this URL:
 * http://involic.com/license.txt
 * If you are unable to obtain it through the world-wide-web,
 * please send an email to license@involic.com so
 * we can send you a copy immediately.
 *
 *
 * Disqus Lite integratation to magento e-commerce platform.
 * Adding comments box for all product page.
 *
 * @category    Involic
 * @package     Involic_Disqus
 * @copyright   Copyright (c) 2011 by Involic (http://www.involic.com)
 * @license     http://involic.com/license.txt
 */

?>

<?php if ($this->isDisqusEnabled()) : ?>
    <div id="disqus_thread"></div>

    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

    <script type="text/javascript">
        //<![CDATA[
        var disqus_shortname = '<?php echo $this->getDisqusForum(); ?>';
        <?php if ($this->getDisqusDeveloper()) : ?>
            var disqus_developer = 1;
        <?php endif; ?>

        var disqus_identifier = '<?php echo $this->getDisqusIdentifier(); ?>';
        var disqus_url = '<?php echo $this->getProductUrl(); ?>';

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';        
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
        //]]>
    </script>
<?php endif; ?>